### ISSUE TITLE
Add "status" prop in Server Routes Return Promise

### ISSUE THREAD

**Issue by DhyeyMoliya** [GrygrFlzr/kit-docs#1]
On the page `learn/data-processing`, you can add a property `status` in the returning promise of server routes.

<img width="922" alt="Screenshot 2021-02-20 at 9 22 14 PM" src="https://user-images.githubusercontent.com/6321840/108601261-beafb280-73c1-11eb-9f70-e7668e924a77.png">

It can be used to return statuses other than `200` (which is default).

**Comment by DhyeyMoliya** [comment]
Same for the `learn/everything` page.

**Comment by GrygrFlzr** [comment]
Added, thanks!
