### ISSUE TITLE
Error Page content sticks

### ISSUE THREAD

**Issue by tobi-or-not-tobi** [GrygrFlzr/kit-docs#2]
According to the instructions (great write up, thanks!), I've added a 404 link to the nav, in order to see the error handling of unknown pages. 

```html
<nav>
    <a href="/">Home</a>
    <a href="/about">About</a>
    <a href="/404">404</a>
</nav>
```

Works like a charm, but the error message sticks on the page. When I navigate to other pages, I keep having the error message. The page seem to refresh and HRM is also broken. I assume it's a bug in svelte, but you guys might know more about it.

**Comment by higsch** [comment]
I experienced the same. You can bypass it (although not optimal) by adding `rel="external"` to your `a` elements.

**Comment by tobi-or-not-tobi** [comment]
thanks @higsch not so much an issue I need to work around for now, just wanted to make sure it's an existing bug rather than a local issue on my side.
